// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system.protobuf

package org.sunyata.game.contract.protobuf.system;

public final class OctopusSystemMessage {
  private OctopusSystemMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginSuccessEventMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userName = 1;
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required int32 userId = 2;
    /**
     * <code>required int32 userId = 2;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 2;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    int getUserId();

    // required int32 gateServerId = 3;
    /**
     * <code>required int32 gateServerId = 3;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    boolean hasGateServerId();
    /**
     * <code>required int32 gateServerId = 3;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    int getGateServerId();
  }
  /**
   * Protobuf type {@code org.sunyata.game.contract.protobuf.system.LoginSuccessEventMsg}
   *
   * <pre>
   *登录请求消息
   * </pre>
   */
  public static final class LoginSuccessEventMsg extends
      com.google.protobuf.GeneratedMessage
      implements LoginSuccessEventMsgOrBuilder {
    // Use LoginSuccessEventMsg.newBuilder() to construct.
    private LoginSuccessEventMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginSuccessEventMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginSuccessEventMsg defaultInstance;
    public static LoginSuccessEventMsg getDefaultInstance() {
      return defaultInstance;
    }

    public LoginSuccessEventMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginSuccessEventMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              gateServerId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg.class, org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginSuccessEventMsg> PARSER =
        new com.google.protobuf.AbstractParser<LoginSuccessEventMsg>() {
      public LoginSuccessEventMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginSuccessEventMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginSuccessEventMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userName = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>required int32 userId = 2;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 userId = 2;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    public int getUserId() {
      return userId_;
    }

    // required int32 gateServerId = 3;
    public static final int GATESERVERID_FIELD_NUMBER = 3;
    private int gateServerId_;
    /**
     * <code>required int32 gateServerId = 3;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    public boolean hasGateServerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 gateServerId = 3;</code>
     *
     * <pre>
     *用户名
     * </pre>
     */
    public int getGateServerId() {
      return gateServerId_;
    }

    private void initFields() {
      userName_ = "";
      userId_ = 0;
      gateServerId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGateServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, gateServerId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, gateServerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.sunyata.game.contract.protobuf.system.LoginSuccessEventMsg}
     *
     * <pre>
     *登录请求消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg.class, org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg.Builder.class);
      }

      // Construct using org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        gateServerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_descriptor;
      }

      public org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg getDefaultInstanceForType() {
        return org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg.getDefaultInstance();
      }

      public org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg build() {
        org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg buildPartial() {
        org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg result = new org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gateServerId_ = gateServerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg) {
          return mergeFrom((org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg other) {
        if (other == org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          bitField0_ |= 0x00000001;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasGateServerId()) {
          setGateServerId(other.getGateServerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserName()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasGateServerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sunyata.game.contract.protobuf.system.OctopusSystemMessage.LoginSuccessEventMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userName = 1;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }

      // required int32 userId = 2;
      private int userId_ ;
      /**
       * <code>required int32 userId = 2;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 userId = 2;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 2;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 2;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      // required int32 gateServerId = 3;
      private int gateServerId_ ;
      /**
       * <code>required int32 gateServerId = 3;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public boolean hasGateServerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 gateServerId = 3;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public int getGateServerId() {
        return gateServerId_;
      }
      /**
       * <code>required int32 gateServerId = 3;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public Builder setGateServerId(int value) {
        bitField0_ |= 0x00000004;
        gateServerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gateServerId = 3;</code>
       *
       * <pre>
       *用户名
       * </pre>
       */
      public Builder clearGateServerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gateServerId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.sunyata.game.contract.protobuf.system.LoginSuccessEventMsg)
    }

    static {
      defaultInstance = new LoginSuccessEventMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.sunyata.game.contract.protobuf.system.LoginSuccessEventMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017system.protobuf\022)org.sunyata.game.cont" +
      "ract.protobuf.system\"N\n\024LoginSuccessEven" +
      "tMsg\022\020\n\010userName\030\001 \002(\t\022\016\n\006userId\030\002 \002(\005\022\024" +
      "\n\014gateServerId\030\003 \002(\005B\026B\024OctopusSystemMes" +
      "sage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_sunyata_game_contract_protobuf_system_LoginSuccessEventMsg_descriptor,
              new java.lang.String[] { "UserName", "UserId", "GateServerId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
